Darken Overlay Background for Light Video Backgrounds
criszz77/react-native-media-console pull request #51
Opened 2023-02-09 20:29 UTC by esegebart

Changed the opacity to be twice as dark so if there is a very light background the controls do not get lost against the video. 
The video is still able to be seen underneath the overlay.

2023-02-09 20:35 UTC, criszz77 requested changes

2023-02-09 20:35 UTC, criszz77 commented on package.json
> +  },
Unfortunately, these should be removed. Is this something that you needed?

2023-02-09 20:36 UTC, criszz77 commented
Looks great! I'll test it tomorrow on my project and see how it looks. Thank you!

2023-02-10 18:44 UTC, esegebart commented
Oh ! Nope I do not need those. I think I added them when I was trying to load the project thinking I needed them, but I don't! I will remove !

2023-02-10 20:07 UTC, criszz77 commented
Don’t worry, just asking. Unfortunately, I didn’t have time to test changes, but I will definitely do it tomorrow. Have a nice weekend!

2023-02-10 20:23 UTC, esegebart commented
@criszz77  If you have time, could you tell me if there is any way to debug / console.log when running or using the media console project? I am trying to understand where data is passed through to see how everything works. Otherwise you have a nice weekend also and I will touch base with you on Monday!

2023-02-10 20:32 UTC, criszz77 commented
Sure. The normal way should work. Just do your changes, and then follow the instrunctions. The logs should appear where you normally check for logs.

2023-02-10 21:05 UTC, esegebart commented
@criszz77 Awesome, thank you so much for your help. :)

2023-02-13 21:24 UTC, criszz77 commented
Hey

Sorry for not giving too much attention as promised... but this week we'll definitely merge it

2023-02-13 21:33 UTC, closed without merging